import 'InfomOrder.dart';

List<Order> getMockOrders() {
  return [
    Order(
      orderId: 'ORD-2024-001',
      customerName: 'Dr. Sarah Johnson',
      customerCity: 'City General Hospital',
      customerEmail: 'sarah.johnson@cityhospital.com',
      customerPhone: '+1 (555) 123-4567',
      customerAddress: '123 Medical Center Dr, New York, NY 10001',
      productName: 'X-Ray Machine Digital (x1)\nPatient Monitor (x2)',
      productQuantity: 3,
      total: 66380,
      status: 'Processing',
      orderDate: '2024-01-15',
      estimatedDelivery: '2024-01-22',
      paymentMethod: 'Bank Transfer',
      notes: 'Urgent delivery required for new ICU setup',
      productPrice: 45000,
    ),
    Order(
      orderId: 'ORD-2024-002',
      customerName: 'Dr. Ahmed Hassan',
      customerCity: 'Medical Center Plus',
      customerEmail: 'ahmed.hassan@medcenterplus.com',
      customerPhone: '+1 (555) 987-6543',
      customerAddress: '456 Healthcare Ave, Los Angeles, CA 90210',
      productName: 'Ultrasound Scanner (x1)',
      productQuantity: 1,
      total: 38100,
      status: 'Shipped',
      orderDate: '2024-01-14',
      estimatedDelivery: '2024-01-18',
      paymentMethod: 'Credit Card',
      notes: 'Standard delivery to radiology department',
      productPrice: 38100,
    ),
    Order(
      orderId: 'ORD-2024-003',
      customerName: 'Dr. Maria Rodriguez',
      customerCity: 'St. Mary\'s Hospital',
      customerEmail: 'maria.rodriguez@stmarys.com',
      customerPhone: '+1 (555) 456-7890',
      customerAddress: '789 Hospital Blvd, Chicago, IL 60601',
      productName: 'Defibrillator (x2)',
      productQuantity: 2,
      total: 59800,
      status: 'Delivered',
      orderDate: '2024-01-13',
      estimatedDelivery: '2024-01-20',
      paymentMethod: 'Bank Transfer',
      notes: 'Emergency equipment for cardiac unit',
      productPrice: 29900,
    ),
    Order(
      orderId: 'ORD-2024-004',
      customerName: 'Dr. Michael Chen',
      customerCity: 'University Medical Center',
      customerEmail: 'michael.chen@umc.edu',
      customerPhone: '+1 (555) 321-0987',
      customerAddress: '321 University Dr, Boston, MA 02115',
      productName: 'MRI Scanner (x1)',
      productQuantity: 1,
      total: 125000,
      status: 'Processing',
      orderDate: '2024-01-12',
      estimatedDelivery: '2024-02-15',
      paymentMethod: 'Lease Agreement',
      notes: 'Installation requires specialized team',
      productPrice: 125000,
    ),
    Order(
      orderId: 'ORD-2024-005',
      customerName: 'Dr. Jennifer Wilson',
      customerCity: 'Children\'s Hospital',
      customerEmail: 'jennifer.wilson@childrens.org',
      customerPhone: '+1 (555) 654-3210',
      customerAddress: '654 Pediatric Way, Seattle, WA 98101',
      productName: 'Ventilator (x3)',
      productQuantity: 3,
      total: 87500,
      status: 'Shipped',
      orderDate: '2024-01-11',
      estimatedDelivery: '2024-01-19',
      paymentMethod: 'Purchase Order',
      notes: 'Pediatric ventilators for NICU',
      productPrice: 29167,
    ),
  ];
}